language: ruby
bundler_args: ""
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.2

cache: bundler

before_script:
  - mysql -u root -e 'DROP DATABASE IF EXISTS arsi_test'
  - mysql -u root -e 'CREATE DATABASE arsi_test CHARACTER SET utf8'

gemfile:
 - gemfiles/rails3.gemfile
 - gemfiles/rails40.gemfile
 - gemfiles/rails41.gemfile

script: bundle exec rake test
