language: ruby
bundler_args: ""
services:
  - mysql
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - ruby-head
sudo: false
cache: bundler
branches:
  only: [master]

before_script:
  - mysql -u root -e 'DROP DATABASE IF EXISTS arsi_test'
  - mysql -u root -e 'CREATE DATABASE arsi_test CHARACTER SET utf8'

gemfile:
 - gemfiles/rails42.gemfile
 - gemfiles/rails50.gemfile
 - gemfiles/rails51.gemfile
 - gemfiles/rails52.gemfile

script: bundle exec rake test

matrix:
  allow_failures:
    - rvm: ruby-head
