language: ruby
bundler_args: ""
rvm:
  - 2.0.0
  - 2.1.5
  - 2.2.2
sudo: false
cache: bundler
branches:
  only: [master]

before_script:
  - mysql -u root -e 'DROP DATABASE IF EXISTS arsi_test'
  - mysql -u root -e 'CREATE DATABASE arsi_test CHARACTER SET utf8'

gemfile:
 - gemfiles/rails3.gemfile
 - gemfiles/rails40.gemfile
 - gemfiles/rails41.gemfile
 - gemfiles/rails42.gemfile

script: bundle exec rake test

matrix:
  exclude:
    - rvm: 2.2.2
      gemfile: gemfiles/rails3.gemfile
