language: ruby
bundler_args: ""
services:
  - mysql
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - ruby-head
sudo: false
cache: bundler
branches:
  only: [master]

before_script:
  - mysql -u root -e 'DROP DATABASE IF EXISTS arsi_test'
  - mysql -u root -e 'CREATE DATABASE arsi_test CHARACTER SET utf8'

gemfile:
 - gemfiles/rails42.gemfile
 - gemfiles/rails50.gemfile

script: bundle exec rake test

matrix:
  exclude:
    - rvm: 2.3
      gemfile: gemfiles/rails40.gemfile
  allow_failures:
    - rvm: ruby-head
